name: docker-build-push


on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Building and pushing docker image to docker.io
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: manishsonawane1998/my-repo
          registry: docker.io
          tags: v1, latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

